### ISSUE TITLE
'--context' request returns an empty result

### ISSUE THREAD

**Issue by nordborn** [TechMagister/cracker#13]
Hello

It looks like the --context request is not working now with Crystal 0.24.2 - it returns an empty result even with your test code on the main page of the repo.
(but the --starts-with is ok).
I've tested by sending requests directly from my console.
Could you check it?

Thanks

**Comment by TechMagister** [comment]
Hello
I'll check this out asap

**Comment by TechMagister** [comment]
It's working for me. Check the crystal source path when launching the server.
